name: Link Check
on: [push, pull_request]

jobs:
  linkcheck:
    # We need an old Ubuntu to get Python 3.6
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - run: pip install -r requirements.txt
    - run: cd ./docs/ && make dirhtml
    - run: cd ./docs/ && make linkcheck

